services:
  users:
    build: ./users
    container_name: users
    image: ghcr.io/pglez82/asw2526_0-users:latest
    ports:
      - "3000:3000"

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: webapp
    image: ghcr.io/pglez82/asw2526_0-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
